### ISSUE TITLE
777-300 and -300ER unable to start

### ISSUE THREAD

**Issue by Bombbird2001** [FGMEMBERS/777#11]
Hi developers,
I downloaded and installed the latest master version of the 777. However, the 777-300 and -300ER do not seem to be able to start (autostart/ground power/battery/APU) so there are no cockpit displays and aircraft systems don't work. I've tried it on 2 different computers both with Windows 10, one with FG2017.1.1 and the other with FG2017.3.1. It does not work on both computers so I don't think it is likely to be a problem with them. The 777-200 and -200ER works fine on both though.

I also have an older version of the 777 (installed on 20 Sept 2016 according to my system) and everything works for that version.

Regards,
Bombbird

**Comment by FGDATA** [comment]
@FGMEMBERS/fg-aircraftdevelopers 

I noticed this too :cry:

**Comment by Bombbird2001** [comment]
It seems that one of the new liveries (the LOVECHINA livery) was causing the bug. I removed that livery and the -300 and -300ER now works fine for me. Not sure what caused the bug but I suspect it might be this portion of the code in the XML file:
`<aircraft-operator>CCA Livery by SLA:ALuo&0762</aircraft-operator>`
I have sent a pull request to remove the livery with some minor changes as well.

**Comment by FGDATA** [comment]
awesome. thanks Bombird!!

**Comment by sidi762** [comment]
Hi, I'm the author of this livery and it works perfectly fine on me and many other people that I known on the current FGAddon version of 777. If the livery was the cause of the bug, I apologize for it. I will do more test on it and if all of them passed, I will push it up again.
Best regards 
Sidi


发自我的 iPhone

**Comment by Bombbird2001** [comment]
I see, I would guess it's the "&" symbol in the `<aircraft-operator>CCA Livery by SLA:ALuo&0762</aircraft-operator>` line that caused the bug (it was highlighted in red here: https://github.com/FGMEMBERS/777/commit/f406312549153b415428f68053c405be612896d2). I didn't change it because I thought it might have been a typo so I'll leave it to the author, so do go ahead and upload it. Nice livery btw :)

Regards,
Bombbird
