### ISSUE TITLE
DualControl

### ISSUE THREAD

**Issue by choyiny** [FGMEMBERS/777#5]
DualControl is missing a display for co-pilot, and co-pilot still cannot control anything.

![13329737_1206142359418166_1822737419_n](https://cloud.githubusercontent.com/assets/1128055/15743927/638a1e6a-28fb-11e6-9843-848e01d45b34.png)

**Comment by FGDATA** [comment]
oh definitely! :)
The dual Control is still work in progress, by @hyde-tech 
When it is more stable he will eventually merge into master. 

If you wish to join the dev team, by all means, go ahead :)

@IAHM-COL
